name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project_evaluator:
    +enabled: false
    

  my_new_project:

    base:
      +database: "PROJECT_SILVER"
      +schema: "STAGING"
      +materialized: view

    staging:
      +database: "PROJECT_SILVER"
      +schema: "STAGING"
      +materialized: view

    marts:
      +database: "PROJECT_GOLD"
      +schema: "MARTS"

      core:
        +materialized: table


flags:
  require_generic_test_arguments_property: true
